#!/bin/bash

gem build piggy_cash.gemspec            # build the gem
gem_name=`ls piggy_cash*.gem`           # get gem name
sudo gem install $gem_name            	# install the gem
rm $gem_name                          	# remove gem file

# piggycash help

# Tags
# piggycash tags recognize			# recognize tags on booking entries, silent
# piggycash tags reveal untagged	# reveal unrecognized bookingentries, silent

# Queries
# piggycash query assign tags		# create, select query and assign tags to it
# piggycash query split VISA		# split single query to multiple

# Stats
# piggycash stats 					# TODO most important values
# piggycash stats saldo				# saldo per month
# piggycash stats monthly				# stats for given month, current month is default

# Setup
# piggycash setup --force
# piggycash setup

# Import
# piggycash import --file ~/Desktop/DIBA_1.csv --encoding ISO-8859-1 --seperator ';' --type ingdiba

# Validate
# piggycash validate saldo

# Serve
piggycash api serve --port 12345
